# Generated by Django 5.0.4 on 2024-05-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horizon', '0002_projects_posts_author_posts_bg_name_posts_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
