# Generated by Django 5.0.4 on 2024-09-15 10:55


from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('Horizon', '0003_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='article',
            field=models.TextField(),
        ),
    ]
