# Generated by Django 5.0.4 on 2024-09-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horizon', '0004_alter_posts_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='article',
            field=models.TextField(),
        ),
    ]
